// ═══════════════════════════════════════════════════════════════
// LANDING PAGES CONTENT — /cennik + /web-na-mieru
// SK (default) / EN / CS / HU
// ═══════════════════════════════════════════════════════════════

export type Locale = 'sk' | 'en' | 'cs' | 'hu';

// ═══ /cennik ═══
export const pricingContent = {
  sk: {
    title: 'Cenník',
    hero: {
      kicker: 'Férová cena, žiadne prekvapenia',
      h1Main: 'Férová cena,',
      h1Highlight: 'žiadne mesačné prekvapenia',
      sub: 'Jednorazová investícia. Web, CMS, AI chatbot — všetko postavené od nuly, bez mesačných poplatkov za cudzie služby.',
      vatNote: 'Všetky ceny sú bez DPH. S DPH 23% pripočítame pri fakturácii.',
    },
    tiers: [
      {
        name: 'Start',
        priceFrom: 'od 990 €',
        priceVat: 'bez DPH  |  s DPH 23%: od 1 217,70 €',
        tagline: 'Web na mieru pre firmy, ktoré potrebujú profesionálnu online vizitku.',
        timeline: 'Realizácia 2–3 týždne',
        features: [
          '4 stránky (domov, o nás, služby, kontakt)',
          'Responzívny dizajn (mobil, tablet, desktop)',
          'Základné SEO a meta tagy',
          'Kontaktný formulár s notifikáciami',
          'Hosting prvý rok zadarmo',
          'Google Analytics + Search Console',
          'SSL certifikát a GDPR cookie banner',
          'Dodanie v 2–3 týždňoch',
        ],
        ctaLabel: 'Mám záujem o Start',
        ctaHref: '/kontakt?balik=start',
        featured: false,
      },
      {
        name: 'Pro',
        priceFrom: 'od 1 990 €',
        priceVat: 'bez DPH  |  s DPH 23%: od 2 447,70 €',
        tagline: 'Web s vlastným CMS — pridávajte články a produkty sami, bez vývojára.',
        timeline: 'Realizácia 3–4 týždne',
        features: [
          'Všetko zo Start balíka',
          '8 stránok + blog / novinky',
          'Vlastný CMS — editujete si obsah sami',
          'Admin panel (správa článkov, galérií, stránok)',
          'SEO audit a optimalizácia (Core Web Vitals)',
          'Integrácia s CRM / mailingom',
          'Multijazyčnosť (SK + EN v cene)',
          'Rozšírená analytika a reporty',
        ],
        ctaLabel: 'Mám záujem o Pro',
        ctaHref: '/kontakt?balik=pro',
        featured: true,
        badge: 'Najpopulárnejší',
      },
      {
        name: 'Enterprise',
        priceFrom: 'od 3 990 €',
        priceVat: 'bez DPH  |  s DPH 23%: od 4 907,70 €',
        tagline: 'Web, AI chatbot a vlastné integrácie — digitálna platforma na mieru.',
        timeline: 'Realizácia 4–6 týždňov',
        features: [
          'Všetko z Pro balíka',
          'Neobmedzený počet stránok',
          'AI chatbot trénovaný na vašich dátach',
          'Vlastné CRM alebo rezervačný systém',
          'Automatizácie (faktúry, emaily, notifikácie)',
          'Prepojenia cez API (Stripe, Supabase, iné)',
          'Priorita pri úpravách a SLA podpora',
          'Dedikovaný projektový manažér',
        ],
        ctaLabel: 'Dohodnime si konzultáciu',
        ctaHref: '/kontakt?balik=enterprise',
        featured: false,
      },
    ],
    addonsLabel: 'Doplnky a rozšírenia',
    addons: [
      { name: 'Logo + vizuálna identita', price: 'od 490 €', desc: 'Logo, farebná paleta, fonty, základný brand manuál.' },
      { name: 'SEO — mesačná správa', price: '290 €/mes', desc: 'Kľúčové slová, content, reporty, technická optimalizácia.' },
      { name: 'AI chatbot integrácia', price: '990 € setup', desc: 'Chatbot trénovaný na vašich dátach, 24/7 zákaznícka podpora.' },
      { name: 'Rozšírenie o jazyk', price: '290 € / jazyk', desc: 'Preklad a lokalizácia obsahu (profesionálny preklad zabezpečíme).' },
      { name: 'E-shop modul', price: 'od 1 490 €', desc: 'Produktový katalóg, košík, Stripe/GoPay platba, objednávky.' },
      { name: 'Rezervačný systém', price: 'od 990 €', desc: 'Online kalendár, platba vopred, notifikácie SMS/email.' },
    ],
    faqLabel: 'Často kladené otázky',
    faqs: [
      {
        q: 'Prečo neúčtujete mesačné poplatky?',
        a: 'Pretože platíte za výsledok, nie za nájom. Web, ktorý vám postavíme, patrí vám — bez mesačnej závislosti na licenciách, šablónach alebo platforme. Mesačné poplatky sú len za hosting (~5 €/mes) alebo rozšírené služby ako SEO.',
      },
      {
        q: 'Prečo nie WordPress alebo Wix?',
        a: 'Lebo tam platíte za šablóny, pluginy, licencie a bezpečnostné aktualizácie každý mesiac. My staviame na Next.js 14 a Vercel — moderný stack, rovnaký ako Nike, TikTok alebo Notion. Rýchlejší, bezpečnejší, bez vendor locku.',
      },
      {
        q: 'Koľko trvá realizácia?',
        a: 'Start balík 2–3 týždne, Pro 3–4 týždne, Enterprise 4–6 týždňov. Čas sa odvíja od dodania obsahu a schválenia dizajnu. Ponúkame fixný harmonogram s míľnikmi.',
      },
      {
        q: 'Čo ak potrebujem úpravy neskôr?',
        a: 'Menšie úpravy (zmena textu, obrázku) si viete urobiť sami cez admin panel (Pro a Enterprise). Väčšie úpravy účtujeme hodinovou sadzbou 55 €/hod bez DPH alebo dohodneme paušál.',
      },
      {
        q: 'Ako prebieha platba?',
        a: '50% preddavok pri podpise zmluvy, 50% po spustení webu. Fakturujeme na s. r. o. (Vassweb s. r. o., IČO 56921021). Prijímame prevod na účet.',
      },
      {
        q: 'Vlastním po zaplatení web?',
        a: 'Áno, bez výhrad. Zdrojový kód, dizajnové súbory, doména, hosting — všetko prejde na vás. Žiadny vendor lock, žiadna závislosť na nás.',
      },
      {
        q: 'Robíte aj aplikácie a AI?',
        a: 'Áno. Okrem webov staviame AI chatboty, natívne mobilné aplikácie (iOS/macOS), CRM systémy a automatizácie. Konzultáciu si dohodneme zdarma.',
      },
      {
        q: 'Aká je záruka?',
        a: '24 mesiacov záruka na kód a dizajn. Ak čokoľvek prestane fungovať kvôli našej chybe, opravíme to zdarma. Platí štandardná slovenská legislatíva.',
      },
    ],
    ctaLabel: 'Vyžiadajte nezáväznú cenovú ponuku',
    ctaSub: 'Ozveme sa do 24 hodín s návrhom a pevnou cenou.',
    ctaBtn: 'Chcem cenovú ponuku',
    breadcrumbHome: 'Domov',
    breadcrumbCurrent: 'Cenník',
  },
  en: {
    title: 'Pricing',
    hero: {
      kicker: 'Fair price, no surprises',
      h1Main: 'Fair price,',
      h1Highlight: 'no monthly surprises',
      sub: 'One-time investment. Website, CMS, AI chatbot — all built from scratch, no monthly fees for third-party services.',
      vatNote: 'All prices are without VAT. With 23% Slovak VAT added on invoice.',
    },
    tiers: [
      {
        name: 'Start',
        priceFrom: 'from €990',
        priceVat: 'excl. VAT  |  incl. VAT 23%: from €1,217.70',
        tagline: 'Custom website for businesses needing a professional online presence.',
        timeline: 'Delivery 2–3 weeks',
        features: [
          '4 pages (home, about, services, contact)',
          'Responsive design (mobile, tablet, desktop)',
          'Basic SEO and meta tags',
          'Contact form with notifications',
          'First year hosting free',
          'Google Analytics + Search Console',
          'SSL certificate and GDPR cookie banner',
          'Delivery in 2–3 weeks',
        ],
        ctaLabel: 'Choose Start',
        ctaHref: '/en/contact?plan=start',
        featured: false,
      },
      {
        name: 'Pro',
        priceFrom: 'from €1,990',
        priceVat: 'excl. VAT  |  incl. VAT 23%: from €2,447.70',
        tagline: 'Website with custom CMS — add articles and products yourself, no developer needed.',
        timeline: 'Delivery 3–4 weeks',
        features: [
          'Everything in Start',
          '8 pages + blog / news',
          'Custom CMS — edit content yourself',
          'Admin panel (articles, galleries, pages)',
          'SEO audit and optimization (Core Web Vitals)',
          'CRM / mailing integration',
          'Multilingual (SK + EN included)',
          'Extended analytics and reports',
        ],
        ctaLabel: 'Choose Pro',
        ctaHref: '/en/contact?plan=pro',
        featured: true,
        badge: 'Most popular',
      },
      {
        name: 'Enterprise',
        priceFrom: 'from €3,990',
        priceVat: 'excl. VAT  |  incl. VAT 23%: from €4,907.70',
        tagline: 'Website, AI chatbot and custom integrations — a digital platform built for you.',
        timeline: 'Delivery 4–6 weeks',
        features: [
          'Everything in Pro',
          'Unlimited pages',
          'AI chatbot trained on your data',
          'Custom CRM or booking system',
          'Automations (invoices, emails, notifications)',
          'API integrations (Stripe, Supabase, etc.)',
          'Priority edits and SLA support',
          'Dedicated project manager',
        ],
        ctaLabel: 'Schedule a consultation',
        ctaHref: '/en/contact?plan=enterprise',
        featured: false,
      },
    ],
    addonsLabel: 'Add-ons and extensions',
    addons: [
      { name: 'Logo + visual identity', price: 'from €490', desc: 'Logo, color palette, fonts, basic brand manual.' },
      { name: 'SEO — monthly retainer', price: '€290/mo', desc: 'Keywords, content, reports, technical optimization.' },
      { name: 'AI chatbot integration', price: '€990 setup', desc: 'Chatbot trained on your data, 24/7 customer support.' },
      { name: 'Additional language', price: '€290 / language', desc: 'Translation and localization (we arrange professional translator).' },
      { name: 'E-shop module', price: 'from €1,490', desc: 'Product catalog, cart, Stripe/GoPay payment, orders.' },
      { name: 'Booking system', price: 'from €990', desc: 'Online calendar, prepayment, SMS/email notifications.' },
    ],
    faqLabel: 'Frequently asked questions',
    faqs: [
      {
        q: 'Why no monthly fees?',
        a: 'Because you pay for the result, not rent. The website we build is yours — no monthly dependency on licenses, templates or platforms. The only monthly cost is hosting (~€5/mo) or optional services like SEO.',
      },
      {
        q: 'Why not WordPress or Wix?',
        a: 'Because you pay for templates, plugins, licenses and security updates every month. We build on Next.js 14 and Vercel — modern stack, the same one used by Nike, TikTok or Notion. Faster, safer, no vendor lock-in.',
      },
      {
        q: 'How long does delivery take?',
        a: 'Start plan 2–3 weeks, Pro 3–4 weeks, Enterprise 4–6 weeks. Timeline depends on content delivery and design approvals. We offer a fixed schedule with milestones.',
      },
      {
        q: 'What if I need changes later?',
        a: 'Minor changes (text, images) you can do yourself via the admin panel (Pro and Enterprise). Larger changes are billed at €55/hr without VAT, or we agree on a retainer.',
      },
      {
        q: 'How does payment work?',
        a: '50% deposit on contract signing, 50% on launch. Invoiced from Vassweb s. r. o. (Company ID 56921021). Bank transfer accepted.',
      },
      {
        q: 'Do I own the website after payment?',
        a: 'Yes, entirely. Source code, design files, domain, hosting — everything transfers to you. No vendor lock-in, no dependency on us.',
      },
      {
        q: 'Do you build apps and AI too?',
        a: 'Yes. Besides websites we build AI chatbots, native mobile apps (iOS/macOS), CRM systems and automations. Free consultation available.',
      },
      {
        q: 'What warranty do you offer?',
        a: '24-month warranty on code and design. If anything breaks due to our fault, we fix it free. Slovak consumer law applies.',
      },
    ],
    ctaLabel: 'Request a no-commitment quote',
    ctaSub: 'We\'ll respond within 24 hours with a proposal and fixed price.',
    ctaBtn: 'Request a quote',
    breadcrumbHome: 'Home',
    breadcrumbCurrent: 'Pricing',
  },
  cs: {
    title: 'Ceník',
    hero: {
      kicker: 'Férová cena, žádná překvapení',
      h1Main: 'Férová cena,',
      h1Highlight: 'žádná měsíční překvapení',
      sub: 'Jednorázová investice. Web, CMS, AI chatbot — vše postavené od nuly, bez měsíčních poplatků za cizí služby.',
      vatNote: 'Všechny ceny jsou bez DPH. S DPH 23% připočteme při fakturaci.',
    },
    tiers: [
      {
        name: 'Start',
        priceFrom: 'od 990 €',
        priceVat: 'bez DPH  |  s DPH 23%: od 1 217,70 €',
        tagline: 'Web na míru pro firmy, které potřebují profesionální online prezentaci.',
        timeline: 'Realizace 2–3 týdny',
        features: [
          '4 stránky (domů, o nás, služby, kontakt)',
          'Responzivní design (mobil, tablet, desktop)',
          'Základní SEO a meta tagy',
          'Kontaktní formulář s notifikacemi',
          'Hosting první rok zdarma',
          'Google Analytics + Search Console',
          'SSL certifikát a GDPR cookie banner',
          'Dodání za 2–3 týdny',
        ],
        ctaLabel: 'Mám zájem o Start',
        ctaHref: '/cs/kontakt?balicek=start',
        featured: false,
      },
      {
        name: 'Pro',
        priceFrom: 'od 1 990 €',
        priceVat: 'bez DPH  |  s DPH 23%: od 2 447,70 €',
        tagline: 'Web s vlastním CMS — přidávejte články a produkty sami, bez vývojáře.',
        timeline: 'Realizace 3–4 týdny',
        features: [
          'Vše ze Start balíčku',
          '8 stránek + blog / novinky',
          'Vlastní CMS — editujete si obsah sami',
          'Admin panel (správa článků, galerií, stránek)',
          'SEO audit a optimalizace (Core Web Vitals)',
          'Integrace s CRM / mailingem',
          'Multijazyčnost (SK + EN v ceně)',
          'Rozšířená analytika a reporty',
        ],
        ctaLabel: 'Mám zájem o Pro',
        ctaHref: '/cs/kontakt?balicek=pro',
        featured: true,
        badge: 'Nejoblíbenější',
      },
      {
        name: 'Enterprise',
        priceFrom: 'od 3 990 €',
        priceVat: 'bez DPH  |  s DPH 23%: od 4 907,70 €',
        tagline: 'Web, AI chatbot a vlastní integrace — digitální platforma na míru.',
        timeline: 'Realizace 4–6 týdnů',
        features: [
          'Vše z Pro balíčku',
          'Neomezený počet stránek',
          'AI chatbot trénovaný na vašich datech',
          'Vlastní CRM nebo rezervační systém',
          'Automatizace (faktury, emaily, notifikace)',
          'Propojení přes API (Stripe, Supabase, jiné)',
          'Priorita při úpravách a SLA podpora',
          'Dedikovaný projektový manažer',
        ],
        ctaLabel: 'Domluvme si konzultaci',
        ctaHref: '/cs/kontakt?balicek=enterprise',
        featured: false,
      },
    ],
    addonsLabel: 'Doplňky a rozšíření',
    addons: [
      { name: 'Logo + vizuální identita', price: 'od 490 €', desc: 'Logo, barevná paleta, fonty, základní brand manuál.' },
      { name: 'SEO — měsíční správa', price: '290 €/měs', desc: 'Klíčová slova, content, reporty, technická optimalizace.' },
      { name: 'AI chatbot integrace', price: '990 € setup', desc: 'Chatbot trénovaný na vašich datech, 24/7 zákaznická podpora.' },
      { name: 'Rozšíření o jazyk', price: '290 € / jazyk', desc: 'Překlad a lokalizace obsahu (profesionální překlad zajistíme).' },
      { name: 'E-shop modul', price: 'od 1 490 €', desc: 'Produktový katalog, košík, Stripe/GoPay platba, objednávky.' },
      { name: 'Rezervační systém', price: 'od 990 €', desc: 'Online kalendář, platba předem, notifikace SMS/email.' },
    ],
    faqLabel: 'Často kladené otázky',
    faqs: [
      {
        q: 'Proč neúčtujete měsíční poplatky?',
        a: 'Protože platíte za výsledek, ne za nájem. Web, který vám postavíme, patří vám — bez měsíční závislosti na licencích, šablonách nebo platformě. Měsíční poplatky jsou jen za hosting (~5 €/měs) nebo rozšířené služby jako SEO.',
      },
      {
        q: 'Proč ne WordPress nebo Wix?',
        a: 'Protože tam platíte za šablony, pluginy, licence a bezpečnostní aktualizace každý měsíc. My stavíme na Next.js 14 a Vercel — moderní stack, stejný jako Nike, TikTok nebo Notion. Rychlejší, bezpečnější, bez vendor locku.',
      },
      {
        q: 'Jak dlouho trvá realizace?',
        a: 'Start balíček 2–3 týdny, Pro 3–4 týdny, Enterprise 4–6 týdnů. Čas se odvíjí od dodání obsahu a schválení designu. Nabízíme fixní harmonogram s milníky.',
      },
      {
        q: 'Co když potřebuji úpravy později?',
        a: 'Menší úpravy (změna textu, obrázku) si můžete udělat sami přes admin panel (Pro a Enterprise). Větší úpravy účtujeme hodinovou sazbou 55 €/hod bez DPH nebo domluvíme paušál.',
      },
      {
        q: 'Jak probíhá platba?',
        a: '50% záloha při podpisu smlouvy, 50% po spuštění webu. Fakturujeme ze s. r. o. (Vassweb s. r. o., IČO 56921021). Přijímáme převod na účet.',
      },
      {
        q: 'Vlastním po zaplacení web?',
        a: 'Ano, bez výhrad. Zdrojový kód, designové soubory, doména, hosting — vše přejde na vás. Žádný vendor lock, žádná závislost na nás.',
      },
      {
        q: 'Děláte i aplikace a AI?',
        a: 'Ano. Kromě webů stavíme AI chatboty, nativní mobilní aplikace (iOS/macOS), CRM systémy a automatizace. Konzultaci si domluvíme zdarma.',
      },
      {
        q: 'Jaká je záruka?',
        a: '24 měsíců záruka na kód a design. Pokud cokoliv přestane fungovat kvůli naší chybě, opravíme to zdarma. Platí standardní spotřebitelská legislativa.',
      },
    ],
    ctaLabel: 'Vyžádejte si nezávaznou cenovou nabídku',
    ctaSub: 'Ozveme se do 24 hodin s návrhem a pevnou cenou.',
    ctaBtn: 'Chci cenovou nabídku',
    breadcrumbHome: 'Domů',
    breadcrumbCurrent: 'Ceník',
  },
  hu: {
    title: 'Árak',
    hero: {
      kicker: 'Tisztességes ár, nincs meglepetés',
      h1Main: 'Tisztességes ár,',
      h1Highlight: 'nincsenek havi meglepetések',
      sub: 'Egyszeri befektetés. Weboldal, CMS, AI chatbot — minden nulláról építve, havi díjak nélkül harmadik fél szolgáltatásaiért.',
      vatNote: 'Minden ár ÁFA nélkül. 23% ÁFÁ-val a számlázáskor.',
    },
    tiers: [
      {
        name: 'Start',
        priceFrom: '990 €-tól',
        priceVat: 'ÁFA nélkül  |  23% ÁFA-val: 1 217,70 €-tól',
        tagline: 'Egyedi weboldal cégeknek, akiknek profi online jelenlétre van szükségük.',
        timeline: 'Elkészítés 2–3 hét',
        features: [
          '4 oldal (főoldal, rólunk, szolgáltatások, kapcsolat)',
          'Reszponzív design (mobil, tablet, asztali)',
          'Alapvető SEO és meta tagek',
          'Kapcsolatfelvételi űrlap értesítésekkel',
          'Első év tárhely ingyen',
          'Google Analytics + Search Console',
          'SSL tanúsítvány és GDPR cookie banner',
          'Szállítás 2–3 héten belül',
        ],
        ctaLabel: 'Start érdekel',
        ctaHref: '/hu/kapcsolat?csomag=start',
        featured: false,
      },
      {
        name: 'Pro',
        priceFrom: '1 990 €-tól',
        priceVat: 'ÁFA nélkül  |  23% ÁFA-val: 2 447,70 €-tól',
        tagline: 'Weboldal saját CMS-szel — cikkek és termékek hozzáadása fejlesztő nélkül.',
        timeline: 'Elkészítés 3–4 hét',
        features: [
          'Minden a Start csomagból',
          '8 oldal + blog / hírek',
          'Saját CMS — tartalmat saját maga szerkeszti',
          'Admin panel (cikkek, galériák, oldalak kezelése)',
          'SEO audit és optimalizálás (Core Web Vitals)',
          'CRM / levelezés integráció',
          'Többnyelvűség (SK + EN az árban)',
          'Bővített analitika és riportok',
        ],
        ctaLabel: 'Pro érdekel',
        ctaHref: '/hu/kapcsolat?csomag=pro',
        featured: true,
        badge: 'Legnépszerűbb',
      },
      {
        name: 'Enterprise',
        priceFrom: '3 990 €-tól',
        priceVat: 'ÁFA nélkül  |  23% ÁFA-val: 4 907,70 €-tól',
        tagline: 'Weboldal, AI chatbot és egyedi integrációk — testreszabott digitális platform.',
        timeline: 'Elkészítés 4–6 hét',
        features: [
          'Minden a Pro csomagból',
          'Korlátlan számú oldal',
          'AI chatbot az Ön adatain tanítva',
          'Saját CRM vagy foglalási rendszer',
          'Automatizálások (számlák, e-mailek, értesítések)',
          'API kapcsolatok (Stripe, Supabase, stb.)',
          'Prioritás a módosításoknál és SLA támogatás',
          'Dedikált projektmenedzser',
        ],
        ctaLabel: 'Egyeztessünk konzultációt',
        ctaHref: '/hu/kapcsolat?csomag=enterprise',
        featured: false,
      },
    ],
    addonsLabel: 'Kiegészítők és bővítmények',
    addons: [
      { name: 'Logó + vizuális identitás', price: '490 €-tól', desc: 'Logó, színpaletta, fontok, alap brand manuál.' },
      { name: 'SEO — havi díj', price: '290 €/hó', desc: 'Kulcsszavak, tartalom, riportok, technikai optimalizálás.' },
      { name: 'AI chatbot integráció', price: '990 € telepítés', desc: 'Chatbot az Ön adatain tanítva, 24/7 ügyfélszolgálat.' },
      { name: 'További nyelv', price: '290 € / nyelv', desc: 'Fordítás és lokalizáció (profi fordítót biztosítunk).' },
      { name: 'E-shop modul', price: '1 490 €-tól', desc: 'Termékkatalógus, kosár, Stripe/GoPay fizetés, megrendelések.' },
      { name: 'Foglalási rendszer', price: '990 €-tól', desc: 'Online naptár, előrefizetés, SMS/e-mail értesítések.' },
    ],
    faqLabel: 'Gyakran ismételt kérdések',
    faqs: [
      {
        q: 'Miért nincsenek havi díjak?',
        a: 'Mert az eredményért fizet, nem a bérleti díjért. A weboldal, amit építünk, az Öné — havi függőség nélkül licencektől, sablonoktól vagy platformoktól. Havi költségek csak a tárhely (~5 €/hó) vagy opcionális szolgáltatások, mint a SEO.',
      },
      {
        q: 'Miért nem WordPress vagy Wix?',
        a: 'Mert ott sablonokért, pluginokért, licencekért és biztonsági frissítésekért fizet minden hónapban. Mi Next.js 14 és Vercel platformra építünk — modern stack, ugyanaz, mint a Nike, TikTok vagy Notion. Gyorsabb, biztonságosabb, vendor lock nélkül.',
      },
      {
        q: 'Mennyi idő az elkészítés?',
        a: 'Start csomag 2–3 hét, Pro 3–4 hét, Enterprise 4–6 hét. Az idő a tartalom leadásától és a design jóváhagyásától függ. Rögzített ütemtervet kínálunk mérföldkövekkel.',
      },
      {
        q: 'Mi van, ha később módosításokra van szükségem?',
        a: 'Kisebb módosításokat (szöveg, kép) maga is elvégezhet az admin panelen (Pro és Enterprise). Nagyobb módosításokat 55 €/óra árral számlázunk ÁFA nélkül, vagy havi díjban állapodunk meg.',
      },
      {
        q: 'Hogyan zajlik a fizetés?',
        a: '50% előleg a szerződés aláírásakor, 50% az indulás után. Vassweb s. r. o.-ból számlázunk (Cégazonosító 56921021). Banki átutalást fogadunk.',
      },
      {
        q: 'Az enyém a weboldal a kifizetés után?',
        a: 'Igen, teljesen. Forráskód, design fájlok, domain, tárhely — minden átkerül Önhöz. Nincs vendor lock, nincs függőség tőlünk.',
      },
      {
        q: 'Építenek alkalmazásokat és AI-t is?',
        a: 'Igen. Weboldalakon kívül AI chatbotokat, natív mobil alkalmazásokat (iOS/macOS), CRM rendszereket és automatizálásokat építünk. Ingyenes konzultáció elérhető.',
      },
      {
        q: 'Milyen garancia van?',
        a: '24 hónap garancia a kódra és designra. Ha bármi elromlik a mi hibánkból, ingyen javítjuk. A szlovák fogyasztóvédelmi jogszabályok érvényesek.',
      },
    ],
    ctaLabel: 'Kérjen kötelezettség nélküli ajánlatot',
    ctaSub: '24 órán belül válaszolunk javaslattal és rögzített árral.',
    ctaBtn: 'Ajánlatot kérek',
    breadcrumbHome: 'Főoldal',
    breadcrumbCurrent: 'Árak',
  },
} as const;

// ═══ /web-na-mieru ═══
export const webContent = {
  sk: {
    title: 'Web na mieru',
    hero: {
      kicker: 'Web na mieru · Next.js · Vercel',
      h1Main: 'Web, ktorý pracuje',
      h1Highlight: 'pre vás 24/7',
      sub: 'Staviame weby od nuly — bez šablón, bez mesačných licencií. Rýchle, bezpečné, navrhnuté na konverzie.',
      stats: [
        { value: '2–6', label: 'týždňov realizácia' },
        { value: '100%', label: 'vlastníctvo kódu' },
        { value: '< 2s', label: 'načítanie stránky' },
      ],
      ctaPrimary: 'Chcem cenovú ponuku',
      ctaPrimaryHref: '/kontakt',
      ctaSecondary: 'Pozrieť cenník',
      ctaSecondaryHref: '/cennik',
    },
    processLabel: 'Ako to prebieha',
    processHeading: '4 kroky od nápadu k spustenému webu',
    process: [
      { num: 'Krok 1', title: 'Brief a konzultácia', desc: 'Zistíme, čo potrebujete a kto sú vaši zákazníci. Bezplatná konzultácia (45 min).', duration: '1–3 dni' },
      { num: 'Krok 2', title: 'Návrh a dizajn', desc: 'Pripravíme wireframe, štruktúru obsahu a vizuálny dizajn v brand identite.', duration: '3–7 dní' },
      { num: 'Krok 3', title: 'Vývoj', desc: 'Kódujeme v Next.js 14, integrujeme CMS, SEO, analytiku a bezpečnosť.', duration: '2–4 týždne' },
      { num: 'Krok 4', title: 'Launch a podpora', desc: 'Spúšťame, školíme vás na admin panel, sledujeme výkon 30 dní zdarma.', duration: '2–3 dni' },
    ],
    stackLabel: 'Na čom staviame',
    stackHeading: 'Moderný stack bez vendor locku',
    stackDesc: 'Používame rovnaké technológie ako Netflix, Nike alebo TikTok — overené, rýchle a budúcnosti otvorené. Po skončení projektu si celý kód odnášate.',
    stack: [
      { name: 'Next.js 14', desc: 'React framework — najrýchlejšie weby na svete.' },
      { name: 'TypeScript', desc: 'Menej chýb, lepšia údržba, profesionálny štandard.' },
      { name: 'Tailwind CSS', desc: 'Moderný dizajn, konzistentný naprieč zariadeniami.' },
      { name: 'Supabase', desc: 'PostgreSQL databáza a autentifikácia — open-source.' },
      { name: 'Vercel', desc: 'Hosting s globálnym CDN, automatické zálohy.' },
      { name: 'Cloudflare', desc: 'DNS, ochrana pred útokmi, SSL certifikát.' },
    ],
    casesLabel: 'Prípadové štúdie',
    casesHeading: 'Výsledky hovoria samé za seba',
    cases: [
      {
        client: 'Rise App',
        industry: 'Fitness SaaS',
        challenge: 'Potrebovali moderný landing page pre spustenie mobilnej aplikácie a zbieranie early accessov.',
        result: 'Landing stránka za 3 týždne. Po spustení reklám 1 200+ beta používateľov za prvý mesiac.',
        metrics: [
          { label: 'Early access', value: '1,2k' },
          { label: 'Conversion rate', value: '4,8%' },
          { label: 'Page speed', value: '98' },
        ],
        href: '/',
        linkLabel: 'Pozrieť projekt',
      },
      {
        client: 'KCars Autobazár',
        industry: 'Automotive',
        challenge: 'Starý web z WordPressu sa načítaval 8 sekúnd, nefungoval na mobile a nemal žiadne dopyty.',
        result: 'Nový web + CRM na mieru. Load time 1,2s. Nárast kvalitných leadov o 340% za 3 mesiace.',
        metrics: [
          { label: 'Nárast leadov', value: '+340%' },
          { label: 'Load time', value: '1,2s' },
          { label: 'Mobile traffic', value: '72%' },
        ],
        href: '/',
        linkLabel: 'Pozrieť projekt',
      },
      {
        client: 'Euphoria Night Club',
        industry: 'Hospitality',
        challenge: 'Klub potreboval rezervačný systém pre VIP stoly a eventy, ktorý funguje aj na mobiloch.',
        result: 'Landing + rezervačný systém s online platbou. 200+ online rezervácií mesačne, odbremenenie recepcie.',
        metrics: [
          { label: 'Online rezervácií/mes', value: '200+' },
          { label: 'Úspora času', value: '15h/týž' },
          { label: 'Spokojnosť', value: '4,9/5' },
        ],
        href: '/',
        linkLabel: 'Pozrieť projekt',
      },
    ],
    testimonialsLabel: 'Čo hovoria klienti',
    testimonials: [
      { quote: 'Richard pochopil náš biznis za 30 minút. Web je rýchly, krásny a dopyty chodia. Odporúčam každému, kto má dosť WordPress reality.', author: 'Zoltán K.', role: 'Majiteľ, KCars' },
      { quote: 'Za 3 týždne sme mali landing page a reklamu. Beta bola plná za mesiac. Profesionálny prístup od začiatku.', author: 'Martin P.', role: 'Founder, Rise App' },
      { quote: 'Pracoval som s troma agentúrami. Vassweb je prvá, ktorá dodala načas, v rozpočte a bez výhovoriek.', author: 'Vlado D.', role: 'Riaditeľ kliniky' },
    ],
    finalCtaLabel: 'Začnime váš projekt',
    finalCtaSub: 'Bezplatná 45-minútová konzultácia. Zistíme, či sme si sadneme — bez záväzkov.',
    finalCtaBtn: 'Chcem konzultáciu',
    pricingLink: 'Pozrieť cenník a balíky',
    pricingLinkHref: '/cennik',
    breadcrumbHome: 'Domov',
    breadcrumbCurrent: 'Web na mieru',
  },
  en: {
    title: 'Custom Website',
    hero: {
      kicker: 'Custom Website · Next.js · Vercel',
      h1Main: 'A website that works',
      h1Highlight: 'for you 24/7',
      sub: 'We build websites from scratch — no templates, no monthly licenses. Fast, secure, designed for conversions.',
      stats: [
        { value: '2–6', label: 'weeks to launch' },
        { value: '100%', label: 'code ownership' },
        { value: '< 2s', label: 'page load time' },
      ],
      ctaPrimary: 'Request a quote',
      ctaPrimaryHref: '/en/contact',
      ctaSecondary: 'See pricing',
      ctaSecondaryHref: '/en/cennik',
    },
    processLabel: 'How it works',
    processHeading: '4 steps from idea to a live website',
    process: [
      { num: 'Step 1', title: 'Brief and consultation', desc: 'We understand what you need and who your customers are. Free 45-min consultation.', duration: '1–3 days' },
      { num: 'Step 2', title: 'Proposal and design', desc: 'We prepare wireframes, content structure and visual design matching your brand.', duration: '3–7 days' },
      { num: 'Step 3', title: 'Development', desc: 'We code in Next.js 14, integrate CMS, SEO, analytics and security.', duration: '2–4 weeks' },
      { num: 'Step 4', title: 'Launch and support', desc: 'We launch, train you on the admin panel, monitor performance 30 days free.', duration: '2–3 days' },
    ],
    stackLabel: 'Our tech stack',
    stackHeading: 'Modern stack, no vendor lock-in',
    stackDesc: 'We use the same technologies as Netflix, Nike or TikTok — proven, fast and future-proof. After the project, you own the entire codebase.',
    stack: [
      { name: 'Next.js 14', desc: 'React framework — the fastest websites in the world.' },
      { name: 'TypeScript', desc: 'Fewer bugs, better maintenance, professional standard.' },
      { name: 'Tailwind CSS', desc: 'Modern design, consistent across devices.' },
      { name: 'Supabase', desc: 'PostgreSQL database and authentication — open-source.' },
      { name: 'Vercel', desc: 'Hosting with global CDN, automatic backups.' },
      { name: 'Cloudflare', desc: 'DNS, DDoS protection, SSL certificate.' },
    ],
    casesLabel: 'Case studies',
    casesHeading: 'Results speak for themselves',
    cases: [
      {
        client: 'Rise App',
        industry: 'Fitness SaaS',
        challenge: 'They needed a modern landing page for a mobile app launch and early access signups.',
        result: 'Landing page in 3 weeks. After launching ads: 1,200+ beta users in the first month.',
        metrics: [
          { label: 'Early access', value: '1.2k' },
          { label: 'Conversion rate', value: '4.8%' },
          { label: 'Page speed', value: '98' },
        ],
        href: '/en',
        linkLabel: 'See project',
      },
      {
        client: 'KCars Car Dealership',
        industry: 'Automotive',
        challenge: 'Their old WordPress site loaded in 8 seconds, didn\'t work on mobile, and generated zero leads.',
        result: 'New website + custom CRM. Load time 1.2s. 340% increase in quality leads over 3 months.',
        metrics: [
          { label: 'Lead growth', value: '+340%' },
          { label: 'Load time', value: '1.2s' },
          { label: 'Mobile traffic', value: '72%' },
        ],
        href: '/en',
        linkLabel: 'See project',
      },
      {
        client: 'Euphoria Night Club',
        industry: 'Hospitality',
        challenge: 'The club needed a booking system for VIP tables and events that works on mobile devices.',
        result: 'Landing + booking system with online payment. 200+ online bookings per month, freed up reception.',
        metrics: [
          { label: 'Bookings/mo', value: '200+' },
          { label: 'Time saved', value: '15h/wk' },
          { label: 'Satisfaction', value: '4.9/5' },
        ],
        href: '/en',
        linkLabel: 'See project',
      },
    ],
    testimonialsLabel: 'What clients say',
    testimonials: [
      { quote: 'Richard understood our business in 30 minutes. The site is fast, beautiful and leads are coming in. Recommended for anyone tired of WordPress.', author: 'Zoltán K.', role: 'Owner, KCars' },
      { quote: 'In 3 weeks we had a landing page and an ad campaign. Beta was full in a month. Professional from start to finish.', author: 'Martin P.', role: 'Founder, Rise App' },
      { quote: 'I worked with three agencies. Vassweb is the first one to deliver on time, within budget and without excuses.', author: 'Vlado D.', role: 'Clinic Director' },
    ],
    finalCtaLabel: 'Let\'s start your project',
    finalCtaSub: 'Free 45-minute consultation. Let\'s see if we\'re a fit — no commitment.',
    finalCtaBtn: 'Book a consultation',
    pricingLink: 'See pricing and packages',
    pricingLinkHref: '/en/cennik',
    breadcrumbHome: 'Home',
    breadcrumbCurrent: 'Custom Website',
  },
  cs: {
    title: 'Web na míru',
    hero: {
      kicker: 'Web na míru · Next.js · Vercel',
      h1Main: 'Web, který pracuje',
      h1Highlight: 'pro vás 24/7',
      sub: 'Stavíme weby od nuly — bez šablon, bez měsíčních licencí. Rychlé, bezpečné, navržené na konverze.',
      stats: [
        { value: '2–6', label: 'týdnů realizace' },
        { value: '100%', label: 'vlastnictví kódu' },
        { value: '< 2s', label: 'načtení stránky' },
      ],
      ctaPrimary: 'Chci cenovou nabídku',
      ctaPrimaryHref: '/cs/kontakt',
      ctaSecondary: 'Podívat se na ceník',
      ctaSecondaryHref: '/cs/cennik',
    },
    processLabel: 'Jak to probíhá',
    processHeading: '4 kroky od nápadu ke spuštěnému webu',
    process: [
      { num: 'Krok 1', title: 'Brief a konzultace', desc: 'Zjistíme, co potřebujete a kdo jsou vaši zákazníci. Bezplatná konzultace (45 min).', duration: '1–3 dny' },
      { num: 'Krok 2', title: 'Návrh a design', desc: 'Připravíme wireframe, strukturu obsahu a vizuální design v brand identitě.', duration: '3–7 dní' },
      { num: 'Krok 3', title: 'Vývoj', desc: 'Kódujeme v Next.js 14, integrujeme CMS, SEO, analytiku a bezpečnost.', duration: '2–4 týdny' },
      { num: 'Krok 4', title: 'Launch a podpora', desc: 'Spouštíme, školíme vás na admin panel, sledujeme výkon 30 dní zdarma.', duration: '2–3 dny' },
    ],
    stackLabel: 'Na čem stavíme',
    stackHeading: 'Moderní stack bez vendor locku',
    stackDesc: 'Používáme stejné technologie jako Netflix, Nike nebo TikTok — ověřené, rychlé a otevřené budoucnosti. Po skončení projektu si celý kód odnášíte.',
    stack: [
      { name: 'Next.js 14', desc: 'React framework — nejrychlejší weby na světě.' },
      { name: 'TypeScript', desc: 'Méně chyb, lepší údržba, profesionální standard.' },
      { name: 'Tailwind CSS', desc: 'Moderní design, konzistentní napříč zařízeními.' },
      { name: 'Supabase', desc: 'PostgreSQL databáze a autentifikace — open-source.' },
      { name: 'Vercel', desc: 'Hosting s globálním CDN, automatické zálohy.' },
      { name: 'Cloudflare', desc: 'DNS, ochrana před útoky, SSL certifikát.' },
    ],
    casesLabel: 'Případové studie',
    casesHeading: 'Výsledky mluví za sebe',
    cases: [
      {
        client: 'Rise App',
        industry: 'Fitness SaaS',
        challenge: 'Potřebovali moderní landing page pro spuštění mobilní aplikace a sběr early accessů.',
        result: 'Landing stránka za 3 týdny. Po spuštění reklam 1 200+ beta uživatelů za první měsíc.',
        metrics: [
          { label: 'Early access', value: '1,2k' },
          { label: 'Conversion rate', value: '4,8%' },
          { label: 'Page speed', value: '98' },
        ],
        href: '/cs',
        linkLabel: 'Podívat se na projekt',
      },
      {
        client: 'KCars Autobazar',
        industry: 'Automotive',
        challenge: 'Starý web z WordPressu se načítal 8 sekund, nefungoval na mobilu a neměl žádné poptávky.',
        result: 'Nový web + CRM na míru. Load time 1,2s. Nárůst kvalitních leadů o 340% za 3 měsíce.',
        metrics: [
          { label: 'Nárůst leadů', value: '+340%' },
          { label: 'Load time', value: '1,2s' },
          { label: 'Mobile traffic', value: '72%' },
        ],
        href: '/cs',
        linkLabel: 'Podívat se na projekt',
      },
      {
        client: 'Euphoria Night Club',
        industry: 'Hospitality',
        challenge: 'Klub potřeboval rezervační systém pro VIP stoly a eventy, který funguje i na mobilech.',
        result: 'Landing + rezervační systém s online platbou. 200+ online rezervací měsíčně, odlehčení recepce.',
        metrics: [
          { label: 'Online rez./měs', value: '200+' },
          { label: 'Úspora času', value: '15h/týd' },
          { label: 'Spokojenost', value: '4,9/5' },
        ],
        href: '/cs',
        linkLabel: 'Podívat se na projekt',
      },
    ],
    testimonialsLabel: 'Co říkají klienti',
    testimonials: [
      { quote: 'Richard pochopil náš byznys za 30 minut. Web je rychlý, krásný a poptávky chodí. Doporučuji každému, kdo má dost WordPress reality.', author: 'Zoltán K.', role: 'Majitel, KCars' },
      { quote: 'Za 3 týdny jsme měli landing page a reklamu. Beta byla plná za měsíc. Profesionální přístup od začátku.', author: 'Martin P.', role: 'Founder, Rise App' },
      { quote: 'Pracoval jsem se třemi agenturami. Vassweb je první, která dodala načas, v rozpočtu a bez výmluv.', author: 'Vlado D.', role: 'Ředitel kliniky' },
    ],
    finalCtaLabel: 'Začněme váš projekt',
    finalCtaSub: 'Bezplatná 45-minutová konzultace. Zjistíme, zda si sedneme — bez závazků.',
    finalCtaBtn: 'Chci konzultaci',
    pricingLink: 'Podívat se na ceník a balíčky',
    pricingLinkHref: '/cs/cennik',
    breadcrumbHome: 'Domů',
    breadcrumbCurrent: 'Web na míru',
  },
  hu: {
    title: 'Egyedi weboldal',
    hero: {
      kicker: 'Egyedi weboldal · Next.js · Vercel',
      h1Main: 'Weboldal, amely dolgozik',
      h1Highlight: 'Önnek 24/7',
      sub: 'Nulláról építünk weboldalakat — sablonok és havi licencek nélkül. Gyors, biztonságos, konverziókra tervezett.',
      stats: [
        { value: '2–6', label: 'hét az indulásig' },
        { value: '100%', label: 'kód tulajdonlás' },
        { value: '< 2s', label: 'oldal betöltés' },
      ],
      ctaPrimary: 'Ajánlatot kérek',
      ctaPrimaryHref: '/hu/kapcsolat',
      ctaSecondary: 'Árak megtekintése',
      ctaSecondaryHref: '/hu/cennik',
    },
    processLabel: 'Hogyan zajlik',
    processHeading: '4 lépés az ötlettől az élő weboldalig',
    process: [
      { num: '1. lépés', title: 'Brief és konzultáció', desc: 'Megértjük, mire van szüksége és kik az ügyfelei. Ingyenes 45 perces konzultáció.', duration: '1–3 nap' },
      { num: '2. lépés', title: 'Javaslat és design', desc: 'Wireframe-et, tartalom struktúrát és vizuális dizájnt készítünk a brand identitásában.', duration: '3–7 nap' },
      { num: '3. lépés', title: 'Fejlesztés', desc: 'Next.js 14-ben kódolunk, CMS-t, SEO-t, analitikát és biztonságot integrálunk.', duration: '2–4 hét' },
      { num: '4. lépés', title: 'Indítás és támogatás', desc: 'Elindítjuk, oktatjuk az admin panelre, 30 napig figyeljük a teljesítményt ingyen.', duration: '2–3 nap' },
    ],
    stackLabel: 'Mire építünk',
    stackHeading: 'Modern stack vendor lock nélkül',
    stackDesc: 'Ugyanazokat a technológiákat használjuk, mint a Netflix, Nike vagy TikTok — bevált, gyors és jövőbiztos. A projekt végén a teljes kódbázis az Öné.',
    stack: [
      { name: 'Next.js 14', desc: 'React keretrendszer — a világ leggyorsabb weboldalai.' },
      { name: 'TypeScript', desc: 'Kevesebb hiba, jobb karbantartás, profi szabvány.' },
      { name: 'Tailwind CSS', desc: 'Modern design, konzisztens eszközökön keresztül.' },
      { name: 'Supabase', desc: 'PostgreSQL adatbázis és hitelesítés — nyílt forráskódú.' },
      { name: 'Vercel', desc: 'Tárhely globális CDN-nel, automatikus mentések.' },
      { name: 'Cloudflare', desc: 'DNS, DDoS védelem, SSL tanúsítvány.' },
    ],
    casesLabel: 'Esettanulmányok',
    casesHeading: 'Az eredmények magukért beszélnek',
    cases: [
      {
        client: 'Rise App',
        industry: 'Fitness SaaS',
        challenge: 'Modern landing oldalra volt szükségük mobil alkalmazás indításához és early access gyűjtéshez.',
        result: 'Landing oldal 3 hét alatt. Hirdetések indítása után 1 200+ béta felhasználó az első hónapban.',
        metrics: [
          { label: 'Early access', value: '1,2k' },
          { label: 'Konverzió', value: '4,8%' },
          { label: 'Oldal sebesség', value: '98' },
        ],
        href: '/hu',
        linkLabel: 'Projekt megtekintése',
      },
      {
        client: 'KCars Autókereskedés',
        industry: 'Autóipar',
        challenge: 'A régi WordPress oldal 8 másodpercig töltődött, nem működött mobilon, és nem generált érdeklődőket.',
        result: 'Új oldal + egyedi CRM. Betöltés 1,2s. 340% növekedés minőségi érdeklődőkben 3 hónap alatt.',
        metrics: [
          { label: 'Lead növekedés', value: '+340%' },
          { label: 'Betöltés', value: '1,2s' },
          { label: 'Mobil forgalom', value: '72%' },
        ],
        href: '/hu',
        linkLabel: 'Projekt megtekintése',
      },
      {
        client: 'Euphoria Night Club',
        industry: 'Vendéglátás',
        challenge: 'A klubnak foglalási rendszerre volt szüksége VIP asztalokhoz és eseményekhez, amely mobilon is működik.',
        result: 'Landing + foglalási rendszer online fizetéssel. 200+ online foglalás havonta, tehermentesített recepció.',
        metrics: [
          { label: 'Foglalás/hó', value: '200+' },
          { label: 'Időmegtakarítás', value: '15ó/hét' },
          { label: 'Elégedettség', value: '4,9/5' },
        ],
        href: '/hu',
        linkLabel: 'Projekt megtekintése',
      },
    ],
    testimonialsLabel: 'Mit mondanak az ügyfelek',
    testimonials: [
      { quote: 'Richard 30 perc alatt megértette a vállalkozásunkat. Az oldal gyors, szép és az érdeklődések jönnek. Ajánlom mindenkinek, aki már elege van a WordPress valóságból.', author: 'Zoltán K.', role: 'Tulajdonos, KCars' },
      { quote: '3 hét alatt volt landing oldalunk és hirdetésünk. A béta egy hónap alatt megtelt. Professzionális hozzáállás az elejétől.', author: 'Martin P.', role: 'Alapító, Rise App' },
      { quote: 'Három ügynökséggel dolgoztam. A Vassweb az első, amely időben, költségvetésen belül és kifogások nélkül szállított.', author: 'Vlado D.', role: 'Klinika igazgató' },
    ],
    finalCtaLabel: 'Kezdjük el a projektjét',
    finalCtaSub: 'Ingyenes 45 perces konzultáció. Lássuk, passzolunk-e — kötelezettség nélkül.',
    finalCtaBtn: 'Konzultációt kérek',
    pricingLink: 'Árak és csomagok megtekintése',
    pricingLinkHref: '/hu/cennik',
    breadcrumbHome: 'Főoldal',
    breadcrumbCurrent: 'Egyedi weboldal',
  },
} as const;

export type PricingLocaleContent = (typeof pricingContent)['sk'];
export type WebLocaleContent = (typeof webContent)['sk'];
